# Generated by Django 3.0 on 2020-12-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
    ]
