# Generated by Django 3.0 on 2020-12-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201218_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Game'),
            preserve_default=False,
        ),
    ]
