# Generated by Django 3.0 on 2020-12-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
